name: EcChunkloader
version: '${project.version}'
main: de.patboyhd.economychunkloader.Main
api-version: 1.19
authors: [ PatBoyHD ]
description: This is a small plugin that lets players forceload chunks in exchange for a set payment.

commands:
  load-chunk:
    description: forceloads a chunk!
  unload-chunk:
    description: un-forceloads a chunk!
  admin-load-chunk:
    description: forceloads a chunk, ignores the per-player limit!
  admin-unload-chunk:
    description: un-forceloads a chunk, no matter who the owner is!
  admin-chunk-count:
    description: Gives the number of forceloaded chunks in form of (chunks/max_allowed_total_chunks)!