name: EcChunkloader
version: '1.0-SNAPSHOT'
main: de.patboyhd.economychunkloader.Main
api-version: 1.19
authors: [ PatBoyHD ]
description: Kleines Plugin, um Spieler gegen Austausch eine Währung Chunks laden zu lassen.

commands:
  load-chunk:
    description: forceloads a chunk!
  unload-chunk:
    description: un-forceloads a chunk!
  admin-load-chunk:
    description: forceloads a chunk, ignores the per-player limit!
  admin-unload-chunk:
    description: un-forceloads a chunk, no matter who the owner is!
  admin-chunk-count:
    description: Gives the number of forceloaded chunks in form of (chunks/max_allowed_chunks)!