name: EcChunkloader
version: '1.0-SNAPSHOT'
main: de.patboyhd.economychunkloader.Main
api-version: 1.19
authors: [ PatBoyHD ]
description: Kleines Plugin, um Spieler gegen Austausch eine Währung Chunks laden zu lassen.

commands:
  load-chunk:
    description: forceloads a Chunk!
  unload-chunk:
    description: un-forceloads a Chunk!